name: PodeIOS
options:
  bundleIdPrefix: com.pode
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  PodeIOS:
    type: application
    platform: iOS
    sources:
      - Sources/PodeIOS
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pode.ios
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
    scheme:
      testTargets:
        - PodeIOSTests
        - PodeIOSUITests
  PodeIOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/PodeIOSTests
    dependencies:
      - target: PodeIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pode.ios.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PodeIOS.app/PodeIOS"
        BUNDLE_LOADER: "$(TEST_HOST)"
  PodeIOSUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/PodeIOSUITests
    dependencies:
      - target: PodeIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pode.ios.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: PodeIOS
